# Generated by Django 3.1.2 on 2020-10-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='update',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created',
        ),
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='update',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='update',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='update',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created',
        ),
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='update',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='update',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='created',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='update',
        ),
        migrations.RemoveField(
            model_name='therapylist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='therapylist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='therapylist',
            name='update',
        ),
        migrations.AddField(
            model_name='medicine',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsession',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapy',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapylist',
            name='abstractmodels_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodels'),
            preserve_default=False,
        ),
    ]
