# Generated by Django 3.1.2 on 2020-10-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201027_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFileOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('filename', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Data File A',
            },
        ),
        migrations.CreateModel(
            name='DataFileTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('filename', models.CharField(max_length=50)),
                ('button', models.PositiveIntegerField()),
                ('correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Data File B',
            },
        ),
    ]
